# Generated by Django 4.1.7 on 2023-02-28 05:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('logoImage', models.CharField(default='https://www.clipartmax.com/png/full/260-2603496_perfume-bottle-outline-free-icon-perfume-bottle-outline.png', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateField(null=True)),
                ('status', models.CharField(choices=[('st', 'Storage'), ('oh', 'On Hold'), ('so', 'Sold')], max_length=2)),
                ('soldDate', models.DateField(null=True)),
                ('manufacturerID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('priceCents', models.IntegerField()),
                ('salePrice', models.IntegerField()),
                ('sizeOz', models.FloatField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Unisex')], max_length=1)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=300)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ca', 'Cart'), ('co', 'Completed')], default='ca', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=5, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='QualityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QualityItemTypeJoin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.itemtype')),
                ('quality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.quality')),
            ],
        ),
        migrations.CreateModel(
            name='QualityCustomerJoin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('quality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.quality')),
            ],
        ),
        migrations.AddField(
            model_name='quality',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.qualitytype'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.shippingaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.itemtype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.shippingaddress'),
        ),
    ]
