# Generated by Django 4.1.5 on 2023-03-01 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='BestSellers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.itemtype')),
            ],
        ),
    ]
